In [54]:
#Import library numpy, pandas dan sclikit-learn
import numpy as np
import pandas as pd
from sklearn import tree

In [55]:
#Membaca dataset dari file ke pandas dataFrame
irisDataset = pd.read_csv('dataset_iris.csv', delimiter=';', header=0)

In [56]:
irisDataset.head()

Id  SepalLengthCm  ...  PetalWidthCm          Species
0   1             11  ...            20  Iris-versicolor
1   2             18  ...            16  Iris-versicolor
2   3             13  ...             7  Iris-versicolor
3   4              4  ...            15  Iris-versicolor
4   5              3  ...            18  Iris-versicolor

[5 rows x 6 columns]

In [57]:
#mengubah kelas (kolom "species") dari string ke unique-integer
irisDataset["Species"] = pd.factorize(irisDataset.Species)[0]

In [58]:
irisDataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1             11             4              8            20        0
1   2             18             7             13            16        0
2   3             13             1              6             7        0
3   4              4             5             15            15        0
4   5              3            10              4            18        0

In [59]:
print(irisDataset)

     Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0     1             11             4              8            20        0
1     2             18             7             13            16        0
2     3             13             1              6             7        0
3     4              4             5             15            15        0
4     5              3            10              4            18        0
..  ...            ...           ...            ...           ...      ...
95   96              5            12             11             3        1
96   97              5            19             10            16        1
97   98              1             3             18            17        1
98   99             15            17             10             8        1
99  100             19            20             12            18        1

[100 rows x 6 columns]


In [60]:
#menghapus kolom "id"
irisDataset = irisDataset.drop(labels="Id", axis=1)

In [61]:
print(irisDataset)

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              11             4              8            20        0
1              18             7             13            16        0
2              13             1              6             7        0
3               4             5             15            15        0
4               3            10              4            18        0
..            ...           ...            ...           ...      ...
95              5            12             11             3        1
96              5            19             10            16        1
97              1             3             18            17        1
98             15            17             10             8        1
99             19            20             12            18        1

[100 rows x 5 columns]


In [62]:
#mengubah dataframe ke array numpy
irisDataset = irisDataset.to_numpy()

In [63]:
print(irisDataset)

[[11  4  8 20  0]
 [18  7 13 16  0]
 [13  1  6  7  0]
 [ 4  5 15 15  0]
 [ 3 10  4 18  0]
 [ 6 14 16 10  0]
 [ 2 12 15 19  0]
 [18 18 15 20  0]
 [14 14  8  4  0]
 [11  5 14  2  0]
 [ 1 18 18  2  0]
 [12  2  4  5  0]
 [10  1 13  5  0]
 [ 3 16 13 20  0]
 [15  6 13 10  0]
 [18  6  2  9  0]
 [18 13 17 13  0]
 [ 5  7  3 12  0]
 [11 13  8  4  0]
 [20 14  6 14  0]
 [13 11 13 12  0]
 [13  4 19  6  0]
 [15  5 19 11  0]
 [ 8 15 18  3  0]
 [ 1  5  6 13  0]
 [12 15 13 19  0]
 [18 16 16  4  0]
 [18  2 18 17  0]
 [ 4  3 20 16  0]
 [ 8 15  4  4  0]
 [ 6  6 19 16  0]
 [ 6 11 11  6  0]
 [19 10  3  9  0]
 [ 3  7  9  4  0]
 [ 8  5  5 18  0]
 [ 8  5 15  3  0]
 [11  8  6  8  0]
 [ 9 13  7 14  0]
 [ 4  4 12  9  0]
 [17 18  8  5  0]
 [ 7  3  9 16  0]
 [17  3 17  5  0]
 [ 8 10 12 19  0]
 [13  6  8 20  0]
 [ 6  1  4 15  0]
 [19  7  8  5  0]
 [ 7 10 16 20  0]
 [20 17 20 16  0]
 [ 9 11 14  1  0]
 [14  8 14  8  0]
 [ 8 10 19  5  1]
 [17 11  6  6  1]
 [ 3 20 12 18  1]
 [17  3  7 18  1]
 [11 14  6  1  1]
 [ 9  1  2

In [64]:
#membagi dataset => 80 baris data untuk training dan 20 baris data untuk testing
dataTraining = np.concatenate((irisDataset[0:40, :], irisDataset[50:90, :]), axis=0)
dataTesting = np.concatenate((irisDataset[40:50, :], irisDataset[90:100, :]), axis=0)                              

In [65]:
print(dataTraining)
len(dataTraining)

[[11  4  8 20  0]
 [18  7 13 16  0]
 [13  1  6  7  0]
 [ 4  5 15 15  0]
 [ 3 10  4 18  0]
 [ 6 14 16 10  0]
 [ 2 12 15 19  0]
 [18 18 15 20  0]
 [14 14  8  4  0]
 [11  5 14  2  0]
 [ 1 18 18  2  0]
 [12  2  4  5  0]
 [10  1 13  5  0]
 [ 3 16 13 20  0]
 [15  6 13 10  0]
 [18  6  2  9  0]
 [18 13 17 13  0]
 [ 5  7  3 12  0]
 [11 13  8  4  0]
 [20 14  6 14  0]
 [13 11 13 12  0]
 [13  4 19  6  0]
 [15  5 19 11  0]
 [ 8 15 18  3  0]
 [ 1  5  6 13  0]
 [12 15 13 19  0]
 [18 16 16  4  0]
 [18  2 18 17  0]
 [ 4  3 20 16  0]
 [ 8 15  4  4  0]
 [ 6  6 19 16  0]
 [ 6 11 11  6  0]
 [19 10  3  9  0]
 [ 3  7  9  4  0]
 [ 8  5  5 18  0]
 [ 8  5 15  3  0]
 [11  8  6  8  0]
 [ 9 13  7 14  0]
 [ 4  4 12  9  0]
 [17 18  8  5  0]
 [ 8 10 19  5  1]
 [17 11  6  6  1]
 [ 3 20 12 18  1]
 [17  3  7 18  1]
 [11 14  6  1  1]
 [ 9  1  2 12  1]
 [12 15  6  8  1]
 [ 7  3 14  2  1]
 [16 18 17 14  1]
 [12 20  5  8  1]
 [19  9  6  5  1]
 [17  8 15  4  1]
 [10  3  6 20  1]
 [10  3 17 10  1]
 [ 7 15 12 13  1]
 [11 16 10

80

In [66]:
print(dataTesting)
len(dataTesting)

[[ 7  3  9 16  0]
 [17  3 17  5  0]
 [ 8 10 12 19  0]
 [13  6  8 20  0]
 [ 6  1  4 15  0]
 [19  7  8  5  0]
 [ 7 10 16 20  0]
 [20 17 20 16  0]
 [ 9 11 14  1  0]
 [14  8 14  8  0]
 [ 2 19 17  7  1]
 [ 2  4  9  2  1]
 [ 1 13 16 15  1]
 [11  3 17 11  1]
 [19 14 18 18  1]
 [ 5 12 11  3  1]
 [ 5 19 10 16  1]
 [ 1  3 18 17  1]
 [15 17 10  8  1]
 [19 20 12 18  1]]


20

In [67]:
#memecah dataset ke input label
inputTraining = dataTraining[:, 0:4]
inputTesting = dataTesting[:, 0:4]
labelTraining = dataTraining[:, 4]
labelTesting = dataTesting[:, 4]
print(labelTraining)
len(labelTraining)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1]


80

In [68]:
#mendefinisikan decision tree classifier
model = tree.DecisionTreeClassifier()

In [69]:
#mentraining model
model = model.fit(inputTraining, labelTraining)

In [70]:
#memprediksi input data testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
Hasil Prediksi :  [1 1 1 0 1 0 1 1 1 1 1 0 0 1 0 0 1 0 1 1]


In [71]:
#menghitung akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar :", prediksiBenar, "data")
print("Prediksi Salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar : 7 data
Prediksi Salah : 13 data
Akurasi : 35.0 %
